virtualcommons/port-of-mars

client/README.md, client/package.json, client/src/api/game/request.ts, client/src/api/tutorial/request.ts, client/src/components/gamedashboard/global/containers/ContainerBoard.vue, client/src/components/gamedashboard/top/containers/ContainerPhase.vue, client/src/router.ts, client/src/store/mutationFolder/notifications.ts, client/src/types/tutorial.ts, client/src/views/Tutorial.vue, client/tests/unit/tutorial.spec.ts, client/yarn.lock
also, made README.md more verbose with respect to running unit tests.
=> feat: tutorial state machine has types. hashtag removed from url.

client/src/components/gamedashboard/bottom/events/views/VoteYesNo.vue, client/src/components/gamedashboard/global/cards/BarAccomplishment.vue, client/src/components/gamedashboard/global/cards/BarDiscard.vue, client/src/components/gamedashboard/global/cards/CardAccomplishment.vue, client/src/components/gamedashboard/global/modals/views/ModalAccomplishment.vue, client/src/plugins/ajax.ts, client/src/views/Login.vue, client/src/views/Tutorial.vue, server/fixtures/Question.yml, server/src/rooms/game/state/marsEvents/state.ts, server/src/routes/middleware.ts, server/src/routes/quiz.ts, server/src/services/quiz.ts, shared/requests.ts
fix: merge conflicts
fix: utilize ajax in tutorial
fix: recent quiz submission returns latest
fix: quiz route statuses
refactor: quiz routes
feat: quiz completion check available
Note:
Not necessarily clear in the PR, but quiz completion status is now set (DB and client) at the end of tutorial completion.
=> feat: quiz-tutorial routes and services complete

server/src/rooms/game/state/marsEvents/state.ts
create variable to get player role
move finalize and toJSON methods to abstract class OutOfCommission
=> refactor: move class methods to OutOfCommission abstract class

client/src/components/gamedashboard/right/Player.vue, client/src/store/getters.ts, server/src/data/MarsEvents.ts, server/src/rooms/game/state/marsEvents/state.ts
create getter isUnderAudit to verify that audit event is drawn for a
round
persists event effects if multiple events are drawn + throughout a round
change v-if on Player component to use isUnderAudit getter
@alee @cpritcha @Nick42791
TODO: fix styling
=> feat: add audit event

client/src/components/gamedashboard/global/cards/CardInvestment.vue
=> fix: display resources that a player can't invest in as disabled

client/src/api/tutorial/request.ts, client/src/api/tutorial/tutorialSteps/discard.ts, client/src/api/tutorial/tutorialSteps/events.ts, client/src/api/tutorial/tutorialSteps/gamePlay.ts, client/src/api/tutorial/tutorialSteps/invest.ts, client/src/api/tutorial/tutorialSteps/notifications.ts, client/src/api/tutorial/tutorialSteps/player.ts, client/src/api/tutorial/tutorialSteps/purchase.ts, client/src/api/tutorial/tutorialSteps/trade.ts, client/src/api/tutorial/tutorialSteps/upkeep.ts, client/src/components/gamedashboard/bottom/containers/ContainerTrade.vue, client/src/components/gamedashboard/bottom/trading/TradeRequest.vue, client/src/components/global/UserHeader.vue, client/src/components/tutorial/TourModal.vue, client/src/stylesheets/layouts/TutorialLayout.scss, client/src/stylesheets/tutorial/TourModal.scss, client/src/types/tutorial.ts, client/src/views/Tutorial.vue
1) Next button is visible, but disabled if you must complete an action before going forward.
2) Quiz radio button restyle
3) Tour Modal at beginning has next button
4) Users must select Trade partner/resource amounts in trade section of tutorial
5) Correct quiz answer message is green, incorrect answer message is large and red
=> [feat]Tutorial Refactor

client/src/api/game/request.ts, client/src/components/gamedashboard/bottom/events/views/InfluencesDraw.vue, client/src/components/gamedashboard/bottom/events/views/VoteYesNo.vue, server/src/data/MarsEvents.ts, server/src/rooms/game/commands/index.ts, server/src/rooms/game/events/index.ts, server/src/rooms/game/index.ts, server/src/rooms/game/state/marsEvents/state.ts, shared/requests.ts
display influence selection view in event bottom container when event is drawn
get current player role
pass player role + associated influence vote to request api 
refactor event to extend BaseGame interface
TODO: complete event functionality on server
=> feat(client): complete BondingThroughAdversity event

server/src/data/MarsEvents.ts, server/src/rooms/game/events/index.ts, server/src/rooms/game/state/marsEvents/MarsEvent.ts, shared/types.ts
If you want to change the time duration of an event, you can. If you do not specify a time, it will run for the default round time.
=> [feat]Event round times are customizable by event

client/src/api/game/response.ts, client/src/components/GameDashboard.vue, client/src/components/gamedashboard/global/containers/ContainerVictory.vue, client/src/store/mutationFolder/gameState.ts, client/src/store/state.ts, client/src/stylesheets/gamedashboard/global/containers/ContainerVictory.scss, server/src/rooms/game/events/index.ts, server/src/rooms/game/state/index.ts, shared/types.ts
note:
* fix build
* closes #199
=> feat: victory screen highlights the winner(s) of the game

client/src/store/getters.ts, server/src/rooms/game/commands/index.ts
- checks upkeep at the following phases: events, purchase, discard
- game over occurs instantaneously 
- add comments to improve code readability
- closes #204
=> refactor(server): end game if upkeep <= 0

client/src/components/gamedashboard/right/Chat.vue
=> fix: strip out whitespace on chat messages (client)

client/src/components/gamedashboard/global/cards/CardInvestment.vue
=> fix: opacity on investment cards is now on the cards themselves

client/src/components/gamedashboard/left/ProfileInvestments.vue, client/src/stylesheets/gamedashboard/left/ProfileInvestments.scss, client/src/stylesheets/gamedashboard/left/containers/ContainerProfile.scss
note:
* fix profile picture overflow
* closes #280
* this is a combination of 2 commits
=> feat: integrate costs into 'your investments' below avatar

client/src/components/gamedashboard/left/ProfileInvestments.vue
=> fix: tooltips / alt text for describing resources

client/src/components/gamedashboard/right/Player.vue
=> fix: audit event view resource count not displaying properly

client/src/api/game/request.ts, client/src/api/game/response.ts, client/src/components/gamedashboard/bottom/containers/ContainerEvents.vue, client/src/components/gamedashboard/bottom/containers/ContainerInvestments.vue, client/src/components/gamedashboard/bottom/events/views/InfluencesSelect.vue, client/src/components/gamedashboard/global/DiscreteStatusBar.vue, client/src/components/gamedashboard/left/ProfileInvestments.vue, client/src/components/gamedashboard/top/Phase.vue, client/src/store/mutationFolder/gameState.ts, client/src/store/mutationFolder/investment.ts, client/src/stylesheets/gamedashboard/bottom/events/EventContainer.scss, client/src/stylesheets/gamedashboard/bottom/events/views/InfluencesSelect.scss, client/src/stylesheets/gamedashboard/global/cards/CardInvestment.scss, server/src/data/MarsEvents.ts, server/src/rooms/game/__tests__/Game.ts, server/src/rooms/game/commands/index.ts, server/src/rooms/game/events/index.ts, server/src/rooms/game/index.ts, server/src/rooms/game/state/index.ts, server/src/rooms/game/state/marsEvents/common.ts, server/src/rooms/game/state/marsEvents/state.ts, shared/requests.ts
feat: Breakdown of trust and Life as usual events
=> feat:Life as Usual and Breakdown of Trust events

client/src/components/gamedashboard/bottom/containers/ContainerTrade.vue, client/src/components/gamedashboard/bottom/trading/Trade.vue, client/src/stylesheets/gamedashboard/bottom/containers/ContainerTrade.scss, client/src/stylesheets/gamedashboard/bottom/trading/Trade.scss, client/src/stylesheets/utilities/_mixins.scss, server/src/rooms/game/events/index.ts
notes:
* refactor: trade component template/sass styling
* todo: trade component gets cut off when screen is zoomed in, large refactor can revisit later
* #295
=> fix: cancel button in trade component

client/src/components/gamedashboard/global/cards/BarAccomplishment.vue, client/src/components/gamedashboard/global/cards/BarDiscard.vue, client/src/components/gamedashboard/global/cards/CardAccomplishment.vue, client/src/components/gamedashboard/global/modals/views/ModalAccomplishment.vue, client/src/stylesheets/gamedashboard/bottom/containers/ContainerInvestments.scss, client/src/stylesheets/gamedashboard/global/cards/BarAccomplishments.scss, client/src/stylesheets/gamedashboard/global/cards/BarDiscard.scss, client/src/stylesheets/gamedashboard/global/cards/CardAccomplishment.scss, client/src/stylesheets/gamedashboard/global/modals/views/ModalAccomplishment.scss
note:
* CardAccomplishment
* BarAccomplishment
* BarDiscard
* ModalAccomplishment
* #295
* this is a combination of 4 commits
=> fix: disabled iconography

client/src/api/tutorial/request.ts, client/src/api/tutorial/tutorialSteps/index.ts, client/src/api/tutorial/tutorialSteps/invest.ts, client/src/api/tutorial/tutorialSteps/trade.ts, client/src/components/gamedashboard/bottom/containers/ContainerInvestments.vue, client/src/components/gamedashboard/bottom/trading/TradeOptions.vue, client/src/components/gamedashboard/bottom/trading/TradeRequest.vue, client/src/store/mutationFolder/trading.ts, client/src/store/state.ts, client/src/types/tutorial.ts, client/src/views/Tutorial.vue, client/tests/unit/common.ts, client/tests/unit/tutorial.spec.ts, shared/types.ts
1) A specific investment must be made
2) A specific trade must be made
3) Required actions(excluding quiz answers) are only required once
=> feat: Tutorial Changes

client/src/components/gamedashboard/top/Phase.vue
note:
* added animation to draw attention to done button (while not clicked)
* #295
=> fix: done button

client/src/api/tutorial/tutorialSteps/trade.ts, client/src/components/gamedashboard/bottom/trading/TradeRequest.vue, client/src/stylesheets/gamedashboard/bottom/trading/TradeRequest.scss
note:
* #295
Tested with the tutorial and everything is working correctly after the modifications.
=> fix: send trade button

client/src/components/gamedashboard/bottom/containers/ContainerInvestments.vue, client/src/components/gamedashboard/global/cards/CardInvestment.vue, client/src/stylesheets/gamedashboard/global/cards/CardInvestment.scss, client/src/stylesheets/utilities/_mixins.scss
=> fix: add investment contributions to CardInvestment component

client/src/components/tutorial/ConsentFormModal.vue, client/src/components/tutorial/TourModal.vue, client/src/store/state.ts, client/src/stylesheets/tutorial/ConsentFormModal.scss, client/src/views/Tutorial.vue
preface tutorial with consent form
create accept/deny buttons on consent form
start tour on accept consent
log out on deny consent
=> feat(client): add consent form to preface tutorial

server/src/data/Accomplishment.ts
=> fix: apostrophes on card text not displaying properly

client/src/components/tutorial/ConsentFormModal.vue, server/src/routes/registration.ts
define route for registering user and email
add email input live feedback and validation
fix styling on consent form
closes #239
=> feat: register user and email on consent form

client/src/store/mutationFolder/index.ts, client/src/store/state.ts, client/src/views/Game.vue
notes:
* added a mutation to reset game state
* closes #269
=> fix: chat duplication

client/src/api/game/request.ts, client/src/api/tutorial/tutorialSteps/invest.ts, client/src/api/tutorial/tutorialSteps/player.ts, client/src/api/tutorial/tutorialSteps/purchase.ts, client/src/components/gamedashboard/bottom/events/views/AccomplishmentsSelectPurchased.vue, client/src/components/gamedashboard/global/cards/BarAccomplishment.vue, client/src/components/gamedashboard/global/cards/CardAccomplishment.vue, client/src/components/gamedashboard/global/modals/views/ModalAccomplishment.vue, client/src/components/gamedashboard/left/containers/ContainerAccomplishments.vue, client/src/store/mutationFolder/accomplishments.ts, client/src/store/mutationFolder/player.ts, client/src/store/state.ts, server/fixtures/Question.yml, server/src/rooms/game/__tests__/Game.ts, server/src/rooms/game/commands/index.ts, server/src/rooms/game/events/index.ts, server/src/rooms/game/index.ts, server/src/rooms/game/state/index.ts, server/src/rooms/game/state/marsEvents/state.ts, shared/requests.ts, shared/types.ts
=> feat: add accomplishment card purchases to mars log

client/src/api/tutorial/tutorialSteps/invest.ts
=> fix: cost on player's unavailable investment = 1001

client/src/components/gamedashboard/bottom/trading/TradeRequest.vue, client/src/stylesheets/gamedashboard/bottom/trading/TradeRequest.scss
=> fix: move send trade button to bottom of request trade container

client/src/components/gamedashboard/bottom/trading/TradeRequest.vue
created destroyed hook in the request component
=> fix:Reset tradeRequest on leave

client/src/api/game/request.ts, client/src/api/tutorial/request.ts, client/src/api/tutorial/tutorialSteps/index.ts, client/src/components/gamedashboard/bottom/trading/Trade.vue, client/yarn.lock, server/src/rooms/game/commands/index.ts, server/src/rooms/game/events/index.ts, server/src/rooms/game/index.ts, server/src/rooms/game/state/index.ts, server/yarn.lock, shared/src/game/requests.ts, shared/src/types.ts
notes:
- closes #270
- fix: distinguish between canceled and declined trades on server
- @alee this is an initial refactor, let me know what you think of the changes. can edit as necessary
- @chrstngyn i added to the mars log enum, feel free to change as necessary
=> refactor: game event encapsulation

client/package.json, client/src/api/game/response.ts, client/src/api/lobby/response.ts, client/src/plugins/ajax.ts, client/src/plugins/tstore.ts, client/src/router.ts, client/src/store/index.ts, client/src/views/Game.vue, client/src/views/WaitingLobby.vue, client/yarn.lock, server/package.json, server/src/index.ts, server/src/rooms/game/commands/index.ts, server/src/rooms/game/index.ts, server/src/rooms/game/state/index.ts, server/src/rooms/game/types.ts, server/src/rooms/lobby/index.ts, server/src/rooms/lobby/state/index.ts, server/src/services/game.ts, server/src/util.ts, server/yarn.lock, shared/src/game/index.ts, shared/src/lobby/index.ts, shared/src/lobby/responses.ts, shared/src/settings.ts
still need to handle auth fails #363 and corner cases
- fixes #352
=> feat: add reconnection support

client/src/api/tutorial/request.ts, client/src/api/tutorial/tutorialSteps/discard.ts, client/src/api/tutorial/tutorialSteps/events.ts, client/src/api/tutorial/tutorialSteps/gamePlay.ts, client/src/api/tutorial/tutorialSteps/invest.ts, client/src/api/tutorial/tutorialSteps/player.ts, client/src/api/tutorial/tutorialSteps/purchase.ts, client/src/api/tutorial/tutorialSteps/trade.ts, client/src/api/tutorial/tutorialSteps/upkeep.ts, client/src/components/GameDashboard.vue, client/src/components/game/HUD.vue, client/src/components/game/PhaseSwitcher.vue, client/src/components/game/modals/ModalController.vue, client/src/components/game/modals/PlayerInfoModal.vue, client/src/components/game/phases/Discard.vue, client/src/components/game/phases/Investments.vue, client/src/components/game/phases/Purchase.vue, client/src/components/game/phases/Trades.vue, client/src/components/game/phases/trade/TradeRequest.vue, client/src/components/game/static/panels/Player.vue, client/src/components/game/static/popups/ActiveEventsPopup.vue, client/src/components/game/static/popups/InventoryPopup.vue, client/src/components/game/static/popups/MarsLogPopup.vue, client/src/components/root/GameboardContainer.vue, client/src/stylesheets/root/GameboardContainer.scss, client/src/stylesheets/views/GameDashboard.scss, client/src/types/tutorial.ts, client/src/views/Tutorial.vue
add available + purchased accomplishments sections to investment phase
implement tour steps for new ui layout + elements
add tour step to highlight + require click on 'ready to advance' button
require player to click on request trade to initiate trade in tutorial
fix game viewport to prevent overflow
temporarily prevent rendering of consent form for testing 
TODO:
add steps to require open/close modals and popups
lingering viewport problems - gameboard shifts when open/close popups during tutorial
=> refactor(tour): implement tour steps for new game interface

client/src/api/dashboard/dashboardAPI.ts, client/src/stylesheets/views/PlayerDashboard.scss, client/src/views/PlayerDashboard.vue, server/src/index.ts, server/src/routes/dashboard.ts, server/src/services/dashboard.ts, server/src/services/index.ts, shared/src/types.ts
to see the player intro/exit surveys, be sure to also go to:
{server endpoint}/dashboard/createInvite
this is temporary, but serves as a way to create an invite for the player you just signed in as.
=> Player dashboard

server/tests/rooms/game/index.test.ts
So, I tried to re-create the error in game, but it the out of commission event was working as expected.
I decided to write a test to be sure, and it's passing. 
Not sure what happened during the playtest.
=> out of commission test on entreprenuer

client/src/components/game/phases/Events.vue, client/src/components/game/phases/events/events/EventNoChange.vue, client/src/stylesheets/game/phases/Events.scss
accomplishment cards are visible when the clientViewHandler is set to:
- INFLUENCES SELECT
- INFLUENCES DRAW
=> feat: accomplishment cards visible in events

client/src/components/game/phases/trade/ActiveTrade.vue, client/src/stylesheets/game/phases/trade/ActiveTrade.scss
notes:
- fix: trade scrollability
- fix: trade cancel iconography
=> fix: trade component issues

client/src/components/game/Inventory.vue, client/src/components/game/modals/PlayerModal.vue, client/src/components/game/modals/TradeRequestModal.vue, client/src/components/game/phases/Discard.vue, client/src/components/game/phases/Purchase.vue, client/src/components/game/static/popups/InventoryPopup.vue
note:
- default prop value keeps contributed system health information hidden (unless specified)
=> fix: inventory component

client/src/components/game/PhaseSwitcher.vue, client/src/stylesheets/game/PhaseSwitcher.scss
nice animation on phase switches.
should close #427.
=> feat: phase switch animation

client/src/stylesheets/game/static/systemhealth/SystemHealth.scss
notes:
- players had an issue with the visibility of the system health status
- increased text size
=> fix: system health text

client/src/api/tutorial/steps/gamePlay.ts, client/src/components/game/HUD.vue, client/src/components/game/static/panels/GameInformation.vue, client/src/components/game/static/panels/PhaseInstructions.vue
=> fix: tutorial explains time remaining

client/src/components/game/phases/Events.vue, client/src/stylesheets/game/phases/Events.scss, client/src/stylesheets/game/phases/events/EventCard.scss, client/src/stylesheets/game/phases/investment/TimeBlockMeter.scss
note:
- event container doesn't overflow when accomplishment cards are added to the view
=> fix: events container

client/src/api/tutorial/steps/index.ts, client/src/api/tutorial/steps/trade.ts, client/src/components/game/phases/Trades.vue, client/src/stylesheets/layouts/TutorialLayout.scss, client/src/views/Tutorial.vue, server/src/services/quiz.ts
pulses unless user hovers over it
could be changed to just a few pulses if it were annoying...
should close #426
=> feat: tutorial tooltip pulses

client/src/components/game/MarsLog.vue, client/src/components/root/ContainerDefeat.vue, client/src/stylesheets/root/ContainerDefeat.scss, server/package-lock.json, server/src/rooms/game/events/index.ts, server/src/rooms/game/state/index.ts, server/src/rooms/game/state/marsEvents/state.ts, shared/src/types.ts
need to refactor log color generation to dictionary that maps the log.category to the color instead of switch-case. this can be done after the play test today
=> feat(mars-log): partition mars logs into rounds at the end of a game

client/src/api/game/request.ts, client/src/api/tutorial/request.ts, client/src/api/tutorial/steps/invest.ts, client/src/components/game/accomplishments/AccomplishmentCard.vue, client/src/components/game/modals/CardModal.vue, client/src/components/game/modals/ModalController.vue, client/src/components/game/modals/PlayerModal.vue, client/src/components/game/phases/Investments.vue, client/src/components/game/phases/Trades.vue, client/src/components/game/phases/events/EventCard.vue, client/src/components/game/phases/events/events/views/InfluencesSelect.vue, client/src/components/game/phases/trade/TradeRequest.vue, client/src/components/game/static/panels/GameInformation.vue, client/src/components/game/static/panels/OtherPlayers.vue, client/src/components/game/static/panels/Player.vue, client/src/components/game/static/popups/ActiveEventsPopup.vue, client/src/components/game/static/popups/InventoryPopup.vue, client/src/components/game/static/popups/MarsLogPopup.vue, client/src/components/game/static/popups/ProfileMenu.vue, client/src/views/Game.vue, client/src/views/Tutorial.vue
- Removed the 'is in tutorial' logic from components
- moved commits to api
- added implicit forward to these steps:
opening modals
all create a trade steps
closing the trade modal
=> Api rework

server/fixtures/Question.yml
=> fix: randomize tutorial question answers

client/src/api/tutorial/request.ts, client/src/api/tutorial/steps/player.ts, client/src/components/game/static/popups/ProfileMenu.vue, client/src/types/tutorial.ts, client/src/views/Tutorial.vue
=> feat: all required actions automatically move forward

client/src/api/game/response.ts, client/src/store/mutations/player.ts
This is very experimental.
It solves the problem of having that switch case in the response.ts game api.
May need to be cleaned up a little but it's a start.
=> fix: clean server responses

client/src/components/game/phases/trade/TradeOptions.vue, client/src/components/game/phases/trade/TradeRequest.vue, shared/src/validation.ts
=> fix: allow altruistic trades

client/src/components/GameDashboard.vue, client/src/components/game/MarsLog.vue, client/src/components/root/ContainerDefeat.vue, client/src/components/root/ContainerVictory.vue, client/src/store/getters.ts, client/src/stylesheets/game/MarsLog.scss, client/src/stylesheets/main.scss, client/src/stylesheets/root/ContainerDefeat.scss, client/src/stylesheets/root/ContainerVictory.scss, server/src/rooms/game/events/index.ts, server/src/rooms/game/state/marsEvents/state.ts, shared/src/types.ts
- add round marker on individual logs
- report contributed system health at the end of a round
- add 'round [x] begins' logs at the beginning of round
- create map of key-value pairs to map log categories to colors
Close #350
=> refactor(mars-log): improve mars log msgs

client/src/api/tutorial/request.ts
=> fix: resetTradeModal call in tutorial

client/src/api/tutorial/steps/invest.ts, client/src/api/tutorial/steps/purchase.ts, client/src/api/tutorial/steps/trade.ts, client/src/components/game/accomplishments/AccomplishmentCard.vue, client/src/components/game/phases/Discard.vue, client/src/components/game/phases/Purchase.vue, client/src/components/tutorial/ConsentFormModal.vue, server/fixtures/Question.yml
should
close #451  
close #485
=> fix: no card references/more emphasis on resource costs

client/src/components/game/phases/Trades.vue, client/src/components/game/phases/trade/ActiveTrade.vue, client/src/stylesheets/game/phases/Trades.scss, client/src/stylesheets/main.scss
Sorting order:
trades sent to you -> color: orange
trades you've sent -> color: orange
trades that don't concern you -> color: white
Additionally, I've added a filter system. The categories are:
Your trades
Trades sent to you
All active trades
should close #477
=> feat: color and sorting for trades

client/src/components/game/phases/trade/ActiveTrade.vue
@chrstngyn @alee 
should close #495
=> fix:hidden trades are always hidden

client/src/components/game/ChatMarsLog.vue, client/src/components/game/MarsLog.vue, client/src/components/game/modals/ModalController.vue, client/src/components/game/modals/PlayerModal.vue, client/src/components/game/modals/TradeRequestModal.vue, client/src/components/game/phases/Discard.vue, client/src/components/game/phases/Events.vue, client/src/components/game/phases/Investments.vue, client/src/components/game/phases/NewRound.vue, client/src/components/game/phases/Purchase.vue, client/src/components/game/phases/Trades.vue, client/src/components/game/phases/investment/InvestmentCard.vue, client/src/components/game/phases/trade/TradeOptions.vue, client/src/components/game/phases/trade/TradeRequest.vue, client/src/stylesheets/main.scss, client/src/views/Dashboard.vue, client/src/views/Login.vue
=> ui improvements to game and onboarding pages

client/src/components/global/Footer.vue, client/src/components/global/Header.vue, client/src/router.ts, client/src/stylesheets/main.scss, client/src/stylesheets/styles.scss, client/src/stylesheets/utilities/_variables.scss, client/src/views/Home.vue, client/src/views/Login.vue, client/src/views/Manual.vue, shared/src/routes.ts
- original mockup and implementation done by Christina Carrasquilla
- same grid layout and css was re-implemented in boostrap vue and optimized for the POM codebase
=> feat: create and finalize styling for Manual using bootstrap vue

client/Dockerfile, client/yarn.lock, server/deploy/Dockerfile.dev, server/deploy/Dockerfile.prod, server/yarn.lock
switch to node:lts-bookworm as base image for client and server
resolves https://github.com/virtualcommons/planning/issues/46
=> upgrade node + yarn deps

client/package.json, client/vite.config.ts, client/yarn.lock
resolves virtualcommons/planning#55
=> build(deps): replace vite-plugin-vue2 with @vitejs/plugin-vue2
